import = [ 
  "~/.config/tmux/plugins/tokyonight.nvim/extras/alacritty/tokyonight_night.toml"
]

[env]
TERM = "xterm-256color"

[window]
decorations = "Buttonless"

opacity = 0.9
blur = true

[font]
size = 22
normal.family = "GoMono Nerd Font Mono"

[keyboard]
bindings = [
  { key="=", mods="Control", action="IncreaseFontSize"},
  { key="-", mods="Control", action="DecreaseFontSize"},

  { key="k", mods="Command", chars="clear\n" },

  { key="Space", mods="Command|Shift", action="ToggleViMode"},

  { key="A", mods="Command", chars="ggVG"}, # select file
  { key = "Left",  mods = "Alt",     chars = "\u001bB", mode="~Alt"   },
  { key = "Right", mods = "Alt",     chars = "\u001bF", mode="~Alt"   },

  { key = "Left",  mods = "Command", chars = "\u001bOH",mode="~Alt"   },
  { key = "Left",  mods = "Command", chars = "§", mode="Alt"   },

  { key = "Right", mods = "Command", chars =  "\u001bOF", mode="~Alt" },
  { key = "Right", mods = "Command", chars =  "¶", mode="Alt" },

  { key = "Back",  mods = "Command", chars = "\u0015", mode="~Alt"     },
  { key = "Back",  mods = "Command", chars = "º", mode="Alt"     },
]
