import = [ 
  "~/.config/tmux/plugins/tokyonight.nvim/extras/alacritty/tokyonight_night.toml"
]

[shell]
program = "/bin/zsh"
args = ["-l", "-c", "tmux attach || tmux"]

[env]
TERM = "xterm-256color"

[window]
decorations = "Buttonless"

opacity = 0.9
blur = true

[font]
size = 22
normal.family = "GoMono Nerd Font Mono"

[keyboard]
bindings = [
  { key="=", mods="Control", action="IncreaseFontSize"},
  { key="-", mods="Control", action="DecreaseFontSize"},

  { key="Space", mods="Command|Shift", action="ToggleViMode"},

  { key="A", mods="Command", chars="ggVG"}, # select file
  { key = "Left",  mods = "Alt",     chars = "\u001bB", mode="~Alt"   },
  { key = "Right", mods = "Alt",     chars = "\u001bF", mode="~Alt"   },

  { key = "Left",  mods = "Command", chars = "\u001bOH",mode="~Alt"   },
  { key = "Left",  mods = "Command", chars = "§", mode="Alt"   },

  { key = "Right", mods = "Command", chars =  "\u001bOF", mode="~Alt" },
  { key = "Right", mods = "Command", chars =  "¶", mode="Alt" },

  { key = "Back",  mods = "Command", chars = "\u0015", mode="~Alt"     },
  { key = "Back",  mods = "Command", chars = "º", mode="Alt"     },

  # tmux mappings
  { key="k", mods="Command", chars="clear\n" },
  # switch sessions
  { key="1", mods="Command", chars="∞s0" },  
  { key="2", mods="Command", chars="∞s1" },  
  { key="3", mods="Command", chars="∞s2" },  
  { key="4", mods="Command", chars="∞s3" },  
  { key="5", mods="Command", chars="∞s5" },  
  # window
  { key = "T", mods = "Command", chars ="∞c" }, # create a new tmux window
  { key = "W", mods = "Command", chars ="∞x" }, # delete current tmux pane
  { key = "N", mods = "Command", chars ="∞e" }, # open new session
]
