#!/usr/bin/env bash

export FZF_DEFAULT_OPTS="$FZF_DEFAULT_OPTS \
  --highlight-line \
  --info=inline-right \
  --ansi \
  --layout=reverse \
  --border=none \
  --color=bg+:#283457 \
  --color=bg:#16161e \
  --color=border:#27a1b9 \
  --color=fg:#c0caf5 \
  --color=gutter:#16161e \
  --color=header:#ff9e64 \
  --color=hl+:#2ac3de \
  --color=hl:#2ac3de \
  --color=info:#545c7e \
  --color=marker:#ff007c \
  --color=pointer:#ff007c \
  --color=prompt:#2ac3de \
  --color=query:#c0caf5:regular \
  --color=scrollbar:#27a1b9 \
  --color=separator:#ff9e64 \
  --color=spinner:#ff007c \
"

export FZF_DEFAULT_OPTS="$FZF_DEFAULT_OPTS \
--no-sort \
--border rounded \
--color=border:#c0caf5 \
--preview-window 'border-rounded' \
--color=preview-border:#27a1b9 \
--bind 'tab:down,btab:up' \
--preview-window 'bottom:40%' \
--height 100% \
--color=bg+:-1 \
--color=bg:-1 \
--no-scrollbar \
--pointer='' 
"
