#!/usr/bin/env bash

/opt/homebrew/bin/tmux display-popup -E -B -w 100% -h 100% \
  'source "$HOME/scripts/fzf-config" && sesh connect "$(sesh list --icons | fzf \
    --border-label " Sesh " \
    --bind "ctrl-d:execute(tmux kill-session -t {2..})+reload(sesh list --icons)" \
    --preview-window "bottom:40%" \
    --preview "sesh preview {}"
  )"'

open -a Ghostty
